name: document
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_slidable: ^3.0.0
  flutter_staggered_animations: ^1.1.1
  freezed_annotation: ^2.4.1
  hive_flutter: ^1.1.0
  image_picker: ^1.0.1
  photo_view: ^0.14.0
  share_plus: 4.0.3
  shared_preferences: ^2.2.0

dev_dependencies:
  build_runner: ^2.4.6
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.1
  hive_generator: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  image_path: "Assets/logo.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "Assets/logo.png"


flutter:
  uses-material-design: true
  assets:
    - Assets/images/homejpg.jpg
    - Assets/images/borderjpg.jpg
